extends Node

signal attack_finished(attacker:CardBaseOnmap, defender:CardBaseOnmap)
signal unit_died(unit:CardBaseOnmap)
signal grid_changed()
signal hand_card_selected_changed(current_selected:CardBaseOnhand)
signal cancel_hand_card_selected()
signal state_changed(from_state: StateBase, to_state: StateBase)
signal deploy_range_found(current_selected:CardBaseOnhand)
signal deploy_range_clear()

signal building_attack()
signal building_skill()
signal vehicle_attack()
signal vehicle_move()
signal vehicle_skill()
signal character_attack()
signal character_move()
signal character_skill()
signal weapon_skill()
signal armor_skill()
